version: '3'
services:

  client:
    container_name: buzzni-test-client
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    image: buzzni-test-client
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./run.py
    ports:
      - "5000:5000"
    volumes:
      - ./client:/client

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /var/log/mongodb/
      MONGODB_USER: "test"
      MONGODB_PASS: "test"
    volumes:
      - ./database/data/db:/data/db
      - ./database/log:/var/log/mongodb/
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/var/log/mongodb/mongod.log

  server:
    container_name: buzzni-test-server
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./run.py
      PYTHONUNBUFFERED: 1
      MONGO_URL: mongodb://mongodb:27017
    image: buzzni-test-server
    ports:
      - "5001:5001"
    volumes:
     - ./server:/server

