version: '3'
services:

  client:
    container_name: buzzni-test-client
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    image: buzzni-test-client
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./run.py
    ports:
      - "5000:5000"
    volumes:
      - ./client:/client

  server:
    container_name: buzzni-test-server
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./run.py
    image: buzzni-test-server
    ports:
      - "5001:5001"
    volumes:
     - ./server:/server

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="test"
      - MONGODB_PASS="test"
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet